language: python
python:
  - "3.6"
before_script:
  - git config credential.helper "store --file=.git/credentials"
  - echo "https://${GH_TOKEN}:@github.com" > .git/credentials
  - git checkout master
script:
  - curl https://raw.githubusercontent.com/gfwlist/gfwlist/master/gfwlist.txt | python -m base64 -d | ./gfwlist2acl.py > gfwlist.acl
  - sed 's/\[bypass_all\]/\[proxy_all\]/' gfwlist.acl | sed 's@/master/gfwlist\.acl@/master/gfwlist.white.acl@' > gfwlist.white.acl
  - git commit -a -m 'Update via travis [skip ci]'
  - git push
branches:
  only:
    - master
