language: python
python:
  - "3.6"
before_script:
  - git config credential.helper "store --file=.git/credentials"
  - echo "https://${GH_TOKEN}:@github.com" > .git/credentials
  - git checkout master
script:
  - curl https://raw.githubusercontent.com/gfwlist/gfwlist/master/gfwlist.txt | python -m base64 -d | ./gfwlist2acl.py > gfwlist.acl
  - sed -e 's/\[bypass_all\]/[proxy_all]/' gfwlist.acl -e 's@/master/gfwlist\.acl@/master/gfwlist.white.acl@' > gfwlist.white.acl
  - sed -i -n  '0,/\[bypass_list]/{/\[bypass_list]/ d};p' gfwlist.acl
  - sed -i -n -e '/\[proxy_list]/,/\[bypass_list]/{/\[bypass_list]/! d};p' gfwlist.white.acl
after_success:
  - git commit -a -m 'Update via travis [skip ci]'
  - git push
branches:
  only:
    - master
