language: python
python:
  - '3.6'
installl:
  - sudo apt-get install -y hub
addons:
  apt:
    update: true
before_script:
  - git config credential.helper "store --file=.git/credentials"
  - echo "https://${GITHUB_TOKEN}:@github.com" > .git/credentials
  - git checkout master
script:
  - pytest
  - ./update.py --release
branches:
  only:
    - master
